Test GET OHLCV bars requests.
axibase/atsd-api-test pull request #741
Opened 2021-06-02 13:35 UTC by MikhailZvagelsky

Tests for ohlcv requests with special trades grouping (periodization). View https://github.com/axibase/tsd/pull/1691 for description.

2021-06-02 13:44 UTC, MikhailZvagelsky commented
Igor, I've tried to reuse yours OHLCV request/response models, and your code to insert trades, and check response lines.
So I've moved corresponding classes and method to separate files.

2021-06-04 12:13 UTC, unrealwork requested changes

2021-06-04 12:13 UTC, unrealwork commented on src/test/kotlin/com/axibase/tsd/api/method/trade/export/Util.kt
> +    val actualFields = actualLine.split(",").toTypedArray()
Сould you parse it to `ResponseLine` class object in separate method and just make one equals assert?

2021-06-04 14:35 UTC, MikhailZvagelsky commented on src/test/kotlin/com/axibase/tsd/api/method/trade/export/Util.kt
> +    val actualFields = actualLine.split(",").toTypedArray()
Implemented.

2021-06-04 16:10 UTC, unrealwork approved these changes

2021-06-07 08:37 UTC, merged